# Generated by Django 4.2.29 on 2026-03-30 09:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('publish_state', models.CharField(choices=[('draft', 'Draft'), ('review', 'In Review'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.SlugField(default='primary', unique=True)),
                ('eyebrow', models.CharField(blank=True, max_length=80)),
                ('title', models.CharField(max_length=180)),
                ('subtitle', models.TextField(blank=True)),
                ('highlight_text', models.CharField(blank=True, max_length=120)),
                ('primary_cta_label', models.CharField(blank=True, max_length=80)),
                ('primary_cta_url', models.URLField(blank=True)),
                ('secondary_cta_label', models.CharField(blank=True, max_length=80)),
                ('secondary_cta_url', models.URLField(blank=True)),
                ('preview_note', models.CharField(blank=True, max_length=255)),
                ('background_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hero_background_for', to='media_library.mediaasset')),
                ('mobile_background_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hero_mobile_background_for', to='media_library.mediaasset')),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Sections',
                'ordering': ('code',),
            },
        ),
    ]
