# Generated by Django 4.2.29 on 2026-03-30 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0002_mediaasset_height_mediaasset_width_and_more'),
        ('hero', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='logo_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hero_logo_for', to='media_library.mediaasset'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='overlay_color',
            field=models.CharField(default='rgba(5,8,20,0.58)', max_length=32),
        ),
        migrations.AddField(
            model_name='herosection',
            name='title_line_two',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='herosection',
            name='visibility_state',
            field=models.CharField(choices=[('visible', 'Visible'), ('hidden', 'Hidden')], db_index=True, default='visible', max_length=16),
        ),
    ]
