# Generated by Django 4.2.29 on 2026-03-30 11:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_library', '0002_mediaasset_height_mediaasset_width_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('visibility_state', models.CharField(choices=[('visible', 'Visible'), ('hidden', 'Hidden')], db_index=True, default='visible', max_length=16)),
                ('publish_state', models.CharField(choices=[('draft', 'Draft'), ('review', 'In Review'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=180)),
                ('eyebrow', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('frame_color', models.CharField(default='#D2A85E', max_length=9, validators=[django.core.validators.RegexValidator(message='Use a hex color such as #0B1020.', regex='^#(?:[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$')])),
                ('ribbon_color', models.CharField(default='#D2A85E', max_length=9, validators=[django.core.validators.RegexValidator(message='Use a hex color such as #0B1020.', regex='^#(?:[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$')])),
                ('text_color', models.CharField(default='#FFFFFF', max_length=9, validators=[django.core.validators.RegexValidator(message='Use a hex color such as #0B1020.', regex='^#(?:[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$')])),
                ('muted_color', models.CharField(default='rgba(255,255,255,0.84)', max_length=20)),
                ('media_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievements_for', to='media_library.mediaasset')),
            ],
            options={
                'verbose_name': 'Achievement',
                'verbose_name_plural': 'Achievements',
                'ordering': ('sort_order', 'created_at'),
            },
        ),
    ]
