# Generated by Django 4.2.29 on 2026-03-30 11:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visibility_state', models.CharField(choices=[('visible', 'Visible'), ('hidden', 'Hidden')], db_index=True, default='visible', max_length=16)),
                ('publish_state', models.CharField(choices=[('draft', 'Draft'), ('review', 'In Review'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.SlugField(default='primary', unique=True)),
                ('brand_text', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('contact_items', models.JSONField(blank=True, default=list)),
                ('social_links', models.JSONField(blank=True, default=list)),
                ('cta_title', models.CharField(blank=True, max_length=150)),
                ('cta_description', models.TextField(blank=True)),
                ('cta_primary_label', models.CharField(blank=True, max_length=80)),
                ('cta_primary_mode', models.CharField(choices=[('login', 'Login'), ('register', 'Register')], default='login', max_length=16)),
                ('cta_secondary_label', models.CharField(blank=True, max_length=80)),
                ('cta_secondary_href', models.CharField(blank=True, max_length=255)),
                ('legal_text', models.CharField(blank=True, max_length=255)),
                ('preview_note', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Footer Section',
                'verbose_name_plural': 'Footer Sections',
                'ordering': ('code',),
            },
        ),
    ]
