# Generated by Django 4.2.29 on 2026-03-30 08:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(default='primary', unique=True)),
                ('site_name', models.CharField(max_length=150)),
                ('site_tagline', models.CharField(blank=True, max_length=255)),
                ('site_description', models.TextField(blank=True)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('support_phone', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('favicon_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_favicon_for', to='media_library.mediaasset')),
                ('logo_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_logo_for', to='media_library.mediaasset')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='ThemeSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('publish_state', models.CharField(choices=[('draft', 'Draft'), ('review', 'In Review'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('theme_name', models.CharField(default='Premium Default', max_length=100)),
                ('brand_primary', models.CharField(default='#0B1020', max_length=9, validators=[django.core.validators.RegexValidator(message='Use a hex color such as #0B1020.', regex='^#(?:[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$')])),
                ('brand_accent', models.CharField(default='#D2A85E', max_length=9, validators=[django.core.validators.RegexValidator(message='Use a hex color such as #0B1020.', regex='^#(?:[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$')])),
                ('background_page', models.CharField(default='#050814', max_length=9, validators=[django.core.validators.RegexValidator(message='Use a hex color such as #0B1020.', regex='^#(?:[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$')])),
                ('background_soft', models.CharField(default='#0F1423', max_length=9, validators=[django.core.validators.RegexValidator(message='Use a hex color such as #0B1020.', regex='^#(?:[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$')])),
                ('text_primary', models.CharField(default='#F4F0E8', max_length=9, validators=[django.core.validators.RegexValidator(message='Use a hex color such as #0B1020.', regex='^#(?:[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$')])),
                ('text_secondary', models.CharField(default='#9BA3B5', max_length=9, validators=[django.core.validators.RegexValidator(message='Use a hex color such as #0B1020.', regex='^#(?:[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$')])),
                ('border_soft', models.CharField(default='#2B3246', max_length=9, validators=[django.core.validators.RegexValidator(message='Use a hex color such as #0B1020.', regex='^#(?:[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$')])),
                ('overlay_hero', models.CharField(default='#0B1020CC', max_length=9, validators=[django.core.validators.RegexValidator(message='Use a hex color such as #0B1020.', regex='^#(?:[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$')])),
                ('surface_white', models.CharField(default='#FFFFFF', max_length=9, validators=[django.core.validators.RegexValidator(message='Use a hex color such as #0B1020.', regex='^#(?:[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$')])),
                ('surface_modal', models.CharField(default='#141B2D', max_length=9, validators=[django.core.validators.RegexValidator(message='Use a hex color such as #0B1020.', regex='^#(?:[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$')])),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theme', to='site_config.sitesettings')),
            ],
            options={
                'verbose_name': 'Theme Settings',
                'verbose_name_plural': 'Theme Settings',
            },
        ),
    ]
