# Generated by Django 4.2.29 on 2026-03-30 11:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='brand_text',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='background_about',
            field=models.CharField(default='#111827', max_length=9, validators=[django.core.validators.RegexValidator(message='Use a hex color such as #0B1020.', regex='^#(?:[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$')]),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='background_achievements',
            field=models.CharField(default='#161E31', max_length=9, validators=[django.core.validators.RegexValidator(message='Use a hex color such as #0B1020.', regex='^#(?:[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$')]),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='background_dark',
            field=models.CharField(default='#02050D', max_length=9, validators=[django.core.validators.RegexValidator(message='Use a hex color such as #0B1020.', regex='^#(?:[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$')]),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='background_light_panel',
            field=models.CharField(default='#1B2740', max_length=9, validators=[django.core.validators.RegexValidator(message='Use a hex color such as #0B1020.', regex='^#(?:[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$')]),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='border_white_soft',
            field=models.CharField(default='rgba(255,255,255,0.12)', max_length=20),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='brand_primary_strong',
            field=models.CharField(default='#9E7A36', max_length=9, validators=[django.core.validators.RegexValidator(message='Use a hex color such as #0B1020.', regex='^#(?:[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$')]),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='brand_secondary',
            field=models.CharField(default='#D2A85E', max_length=9, validators=[django.core.validators.RegexValidator(message='Use a hex color such as #0B1020.', regex='^#(?:[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$')]),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='brand_soft',
            field=models.CharField(default='#F1DFBF', max_length=9, validators=[django.core.validators.RegexValidator(message='Use a hex color such as #0B1020.', regex='^#(?:[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$')]),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='mobile_hero_bottom_nav_background',
            field=models.CharField(default='rgba(10,15,28,0.92)', max_length=20),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='mobile_hero_bottom_nav_text_color',
            field=models.CharField(default='#F4F0E8', max_length=9, validators=[django.core.validators.RegexValidator(message='Use a hex color such as #0B1020.', regex='^#(?:[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$')]),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='mobile_hero_nav_shadow',
            field=models.CharField(default='0 18px 42px rgba(0, 0, 0, 0.22)', max_length=80),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='mobile_hero_soft_shadow',
            field=models.CharField(default='0 16px 36px rgba(0, 0, 0, 0.28)', max_length=80),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='mobile_hero_top_icon_inner_background',
            field=models.CharField(default='#FFFFFF', max_length=9, validators=[django.core.validators.RegexValidator(message='Use a hex color such as #0B1020.', regex='^#(?:[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$')]),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='mobile_hero_top_icon_outer_background',
            field=models.CharField(default='#8B5F2E', max_length=9, validators=[django.core.validators.RegexValidator(message='Use a hex color such as #0B1020.', regex='^#(?:[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$')]),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='overlay_modal',
            field=models.CharField(default='rgba(5,8,20,0.82)', max_length=20),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='overlay_navbar',
            field=models.CharField(default='rgba(5,8,20,0.72)', max_length=20),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='surface_glass',
            field=models.CharField(default='rgba(255,255,255,0.12)', max_length=20),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='text_muted',
            field=models.CharField(default='#7F8AA3', max_length=9, validators=[django.core.validators.RegexValidator(message='Use a hex color such as #0B1020.', regex='^#(?:[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$')]),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='text_soft',
            field=models.CharField(default='#C1C8D6', max_length=9, validators=[django.core.validators.RegexValidator(message='Use a hex color such as #0B1020.', regex='^#(?:[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$')]),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='text_white',
            field=models.CharField(default='#FFFFFF', max_length=9, validators=[django.core.validators.RegexValidator(message='Use a hex color such as #0B1020.', regex='^#(?:[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$')]),
        ),
    ]
