# Generated by Django 4.2.29 on 2026-03-30 09:13

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('publish_state', models.CharField(choices=[('draft', 'Draft'), ('review', 'In Review'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('sku', models.CharField(blank=True, max_length=80)),
                ('short_description', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('cover_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_cover_for', to='media_library.mediaasset')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ('sort_order', 'title', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='ProductTheme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accent_color', models.CharField(default='#D2A85E', max_length=9, validators=[django.core.validators.RegexValidator(message='Use a hex color such as #0B1020.', regex='^#(?:[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$')])),
                ('surface_color', models.CharField(default='#111A2D', max_length=9, validators=[django.core.validators.RegexValidator(message='Use a hex color such as #0B1020.', regex='^#(?:[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$')])),
                ('text_color', models.CharField(default='#F4F0E8', max_length=9, validators=[django.core.validators.RegexValidator(message='Use a hex color such as #0B1020.', regex='^#(?:[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$')])),
                ('badge_label', models.CharField(blank=True, max_length=60)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theme', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Theme',
                'verbose_name_plural': 'Product Themes',
            },
        ),
    ]
