# Generated by Django 4.2.29 on 2026-03-30 11:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0002_mediaasset_height_mediaasset_width_and_more'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='badge',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='product',
            name='cart_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='order_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='saved_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='subtitle',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='product',
            name='visibility_state',
            field=models.CharField(choices=[('visible', 'Visible'), ('hidden', 'Hidden')], db_index=True, default='visible', max_length=16),
        ),
        migrations.AddField(
            model_name='producttheme',
            name='card_color',
            field=models.CharField(default='#172236', max_length=9, validators=[django.core.validators.RegexValidator(message='Use a hex color such as #0B1020.', regex='^#(?:[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$')]),
        ),
        migrations.AddField(
            model_name='producttheme',
            name='media_panel_color',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='producttheme',
            name='media_panel_mode',
            field=models.CharField(choices=[('image_tone', 'Image Tone'), ('force_black', 'Force Black'), ('force_white', 'Force White')], default='force_black', max_length=16),
        ),
        migrations.AddField(
            model_name='producttheme',
            name='muted_color',
            field=models.CharField(default='#9BA3B5', max_length=9, validators=[django.core.validators.RegexValidator(message='Use a hex color such as #0B1020.', regex='^#(?:[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$')]),
        ),
        migrations.AddField(
            model_name='producttheme',
            name='tone',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='dark', max_length=16),
        ),
        migrations.CreateModel(
            name='ProductMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('visibility_state', models.CharField(choices=[('visible', 'Visible'), ('hidden', 'Hidden')], db_index=True, default='visible', max_length=16)),
                ('publish_state', models.CharField(choices=[('draft', 'Draft'), ('review', 'In Review'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('label', models.CharField(blank=True, max_length=80)),
                ('role', models.CharField(choices=[('primary', 'Primary'), ('gallery', 'Gallery'), ('detail', 'Detail')], default='gallery', max_length=16)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_media_links', to='media_library.mediaasset')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Media',
                'verbose_name_plural': 'Product Media',
                'ordering': ('sort_order', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('visibility_state', models.CharField(choices=[('visible', 'Visible'), ('hidden', 'Hidden')], db_index=True, default='visible', max_length=16)),
                ('publish_state', models.CharField(choices=[('draft', 'Draft'), ('review', 'In Review'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=80)),
                ('hex_color', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='Use a hex color such as #0B1020.', regex='^#(?:[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$')])),
                ('preview_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_color_previews', to='media_library.mediaasset')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_variants', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Color',
                'verbose_name_plural': 'Product Colors',
                'ordering': ('sort_order', 'created_at'),
            },
        ),
    ]
